# config/config.yaml

config:
  delete_old_screenshots: 1
  # This allows you to decide if you want to keep old screenshots (ones that are not in use anymore.)
  # If you set this to 1, it will delete old screenshots.
  # If you set this to 0, it will not delete old screenshots.



ui:
  question_region: [[1198, 473], [2289, 475], [2291, 887], [1194, 889]]
  # Question_region is preconfigure for a 1920x1080 screen
  # If your screen is not 1920x1080, you will need to change these values manually
  # The larger the screenshot the longer it will take for a response.
  # This is formatted X1, X2, Y1, Y2 (x being the top corners, and y being the bottom corners.)
  # The easiest way to get these values is to use the screenshot tool in the utiliy folder.
  # You can run it with the command `python -m utilities.mouse-position` and it will come back with the coordinates of your mouse each time you click. 

debug:
  enabled: 1
  level: "debug"
  # log_level includes debug, minimal 
  # This edits the logging level.
  # If you do not want to see debug messages, set this to minimal, and if you seriously don't want to see any messages at all (not recommended) set enabled to 0.
