# config/config.yaml

config:
  # Most things listed in here are booleans, 1 is true and 0 is false (1: yes 2: no)
  answer_automatically: 1
  # Answer automatically lets you decide if you want the program to automatically answer
  # or just give you the answer allowing you to answer manually (less error prone but not as convinent.)
  delete_old_screenshots: 1
  # This allows you to decide if you want to keep old screenshots (ones that are not in use anymore.)



ui:
  question_region: [[667, 442], [1361, 463], [1371, 712], [776, 720]]
  # Question_region is preconfigure for a 1920x1080 screen
  # If your screen is not 1920x1080, you will need to change these values manually
  # The larger the screenshot the longer it will take for a response.
  # This is formatted X1, X2, Y1, Y2 (x being the top corners, and y being the bottom corners.)


system:
  tesseract_cmd: "/usr/bin/tesseract" # Linux Configuration
  # tesseract_cmd: "C:\\Program Files\\Tesseract-OCR\\tesseract.exe" # Windows config
  # /opt/homebrew/bin/tesseract # Apple Silicon MAC
  # /usr/local/bin/tesseract # Intel based MAC

debug:
  log_level: "debug"
  # log_level includes debug, minimal and none.
  # This edits the logging level.
